development:
  adapter: mysql2
  encoding: utf8
  database: mp_dev
  pool: 5
  username: mp_admin
  password: Pabopovib234.
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: mp_test
  pool: 5
  username: mp_admin
  password: Pabopovib234.
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: mp_prod
  pool: 5
  username: mp_admin
  password: Pabopovib234.
  socket: /var/run/mysqld/mysqld.sock

